var xl = [
{
name:"万能接口：api.xfsub.com",
url:"http://api.xfsub.com/index.php?url=",
},
{
name:"万能接口：beaacc.com",
url:"https://beaacc.com/api.php?url=",
},
{
name:"万能接口：y.mt2t.com",
url:"http://y.mt2t.com/lines?url=",
},
{
name:"万能接口：jiexi.071811.cc",
url:"http://jiexi.071811.cc/jx2.php?url=",
},
{
name:"万能接口：www.662820.com",
url:"http://www.662820.com/xnflv/index.php?url=",
},
{
name:"万能接口：api.91exp.com",
url:"http://api.91exp.com/svip/?url=",
},
{
name:"万能接口：player.jidiaose.com",
url:"http://player.jidiaose.com/supapi/iframe.php?v=",
},
{
name:"万能接口：jx.598110.com①",
url:"http://jx.598110.com/zuida.php?url=",
},
{
name:"万能接口：jx.598110.com②",
url:"http://jx.598110.com/duo/index.php?url=",
},
{
name:"万能接口：jx.598110.com③",
url:"http://jx.598110.com/index.php?url=",
}
]
