var xl = [
{
name:"万能接口",
url:"http://api.xfsub.com/index.php?url=",
},
{
name:"万能接口",
url:"https://beaacc.com/api.php?url=",
},
{
name:"万能接口,
url:"http://y.mt2t.com/lines?url=",
},
{
name:"万能接口",
url:"http://jiexi.071811.cc/jx2.php?url=",
},
{
name:"万能接口",
url:"http://www.662820.com/xnflv/index.php?url=",
},
{
name:"万能接口",
url:"http://api.91exp.com/svip/?url=",
},
{
name:"万能接口",
url:"http://player.jidiaose.com/supapi/iframe.php?v=",
},
{
name:"万能接口",
url:"http://jx.598110.com/zuida.php?url=",
},
{
name:"万能接口",
url:"http://jx.598110.com/duo/index.php?url=",
},
{
name:"万能接口",
url:"http://jx.598110.com/index.php?url=",
}
]
